#' Load Drainage Division Data
#'
#' This function loads spatial data for one or more drainage divisions from the
#' \code{ausrivRdata} package. Data layers available include 
#' \code{"AWRADrainageDivision"}, \code{"RiverRegion"}, \code{"AHGFNetworkStream"}, 
#' and \code{"AHGFWaterbody"}. The function returns a list of \code{sf} objects for each
#' specified division. When multiple division names are provided, the returned list is named
#' using a standardized version of each division name (spaces and hyphens replaced by underscores,
#' all lowercase).
#'
#' @param division_name Character; name (or vector of names) of the drainage division(s).
#' @param layers Character vector; which layers to load (e.g., \code{"AWRADrainageDivision"}, 
#'               \code{"RiverRegion"}, \code{"AHGFNetworkStream"}, \code{"AHGFWaterbody"}). 
#'               Default loads all.
#'
#' @return For a single division name, a list of \code{sf} objects for that drainage division.
#'         For multiple division names, a named list where each element is the list of \code{sf} objects
#'         for that division. The names of the list are generated by applying the \code{.standardize_name}
#'         helper function to each supplied division name.
#'
#' @details
#' The function first attempts to match the supplied division name(s) to a known set of abbreviations 
#' (provided in the internal \code{.division_name_map}). If a match is found (exact or case-insensitive), 
#' the corresponding abbreviated directory is used to locate data files. The supplied division name is also 
#' standardized (spaces and hyphens replaced with underscores, non-alphanumeric characters removed, and converted
#' to lowercase) to form part of the filename. Data are then loaded for the requested layers.
#'
#' @examples
#' \dontrun{
#' # Example 1: Load RiverRegion data for a single drainage division.
#' river_region_data <- load_drainage_division(
#'   division_name = "Murray-Darling Basin",
#'   layers = "RiverRegion"
#' )
#'
#' # Example 2: Load RiverRegion data for multiple drainage divisions.
#' # The returned list will have names "murray_darling_basin" and "south_australian_gulf".
#' multi_division_data <- load_drainage_division(
#'   division_name = c("Murray-Darling Basin", "South Australian Gulf"),
#'   layers = "RiverRegion"
#' )
#'
#' # Access data for the South Australian Gulf division:
#' sa_data <- multi_division_data[["south_australian_gulf"]]
#' }
#'
#' @importFrom sf st_make_valid
#' @importFrom stringr str_replace_all str_to_title
#' @importFrom magrittr %>%
#' @export
load_drainage_division <- function(division_name, 
                                   layers = c("AWRADrainageDivision", "RiverRegion", 
                                              "AHGFNetworkStream", "AHGFWaterbody")) {
  # If more than one division is specified, iterate and return a named list
  if (length(division_name) > 1) {
    result <- lapply(division_name, function(div) {
      load_drainage_division(division_name = div, layers = layers)
    })
    names(result) <- sapply(division_name, .standardize_name)
    return(result)
  }
  
  # Proceed with single division name
  matched_dir <- NULL
  
  # First try exact match
  if (division_name %in% names(.division_name_map)) {
    matched_dir <- .division_name_map[[division_name]]
  } else {
    # Try case-insensitive match
    idx <- which(tolower(names(.division_name_map)) == tolower(division_name))
    if (length(idx) == 1) {
      matched_dir <- .division_name_map[[idx]]
    }
  }
  
  if (is.null(matched_dir)) {
    stop("Invalid division name: '", division_name, "'\n",
         "Available divisions:\n", paste("-", names(.division_name_map), collapse = "\n"))
  }
  
  # Get base directory
  base_dir <- system.file("extdata/spatial", matched_dir, package = "ausrivRdata")
  if (base_dir == "") {
    stop("Data directory not found for division: ", division_name)
  }
  
  # Get standardized name for filenames
  std_name <- .standardize_name(division_name)
  
  # Initialize results list
  division_data <- list()
  
  # Load requested layers
  for (layer in layers) {
    filename <- file.path(base_dir, paste0(layer, "_", std_name, ".rds"))
    
    if (file.exists(filename)) {
      tryCatch({
        # Load and validate geometry
        data <- readRDS(filename) %>% st_make_valid()
        division_data[[layer]] <- data
        message("Loaded ", layer, " for ", division_name)
      }, error = function(e) {
        warning("Error loading ", layer, ": ", e$message)
        NULL
      })
    } else {
      warning("File not found for layer '", layer, "'")
    }
  }
  
  # Check if any data was loaded
  if (length(division_data) == 0) {
    stop("No data could be loaded for division '", division_name, "'")
  }
  
  return(division_data)
}
